"""Main Test Generator"""
import os
import sys
from typing import List, Dict, Any

# Add parent directory to path for imports
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from parsers.problem_parser import ProblemParser, TestStep
from templates.ui_templates import UITemplates
from templates.api_templates import APITemplates
from templates.mobile_templates import MobileTemplates

class TestGenerator:
    def __init__(self, output_dir: str = "generated_tests"):
        self.parser = ProblemParser()
        self.ui_templates = UITemplates()
        self.api_templates = APITemplates()
        self.mobile_templates = MobileTemplates()
        
        # Make output directory absolute
        if not os.path.isabs(output_dir):
            self.output_dir = os.path.abspath(output_dir)
        else:
            self.output_dir = output_dir
        
        # Create output directory if it doesn't exist
        os.makedirs(self.output_dir, exist_ok=True)
    
    def generate_from_problem_statement(self, problem_text: str, test_name: str = "AutoGenerated") -> Dict[str, str]:
        # Parse problem statement
        steps = self.parser.parse_problem_statement(problem_text)
        
        # Generate test files
        generated_files = {}
        
        # Generate UI tests
        ui_steps = [step for step in steps if step.step_type == 'ui']
        if ui_steps:
            ui_code = self._generate_ui_test(ui_steps, f"{test_name}_UI")
            generated_files['ui_test.py'] = ui_code
        
        # Generate API tests
        api_steps = [step for step in steps if step.step_type == 'api']
        if api_steps:
            api_code = self._generate_api_test(api_steps, f"{test_name}_API")
            generated_files['api_test.py'] = api_code
        
        # Generate Mobile tests
        mobile_steps = [step for step in steps if step.step_type == 'mobile']
        if mobile_steps:
            mobile_code = self._generate_mobile_test(mobile_steps, f"{test_name}_Mobile")
            generated_files['mobile_test.py'] = mobile_code
        
        # Generate integration test
        integration_code = self._generate_integration_test(steps, f"{test_name}_Integration")
        generated_files['integration_test.py'] = integration_code
        
        return generated_files
    
    def _generate_ui_test(self, ui_steps: List[TestStep], class_name: str) -> str:
        test_code_lines = []
        
        for step in ui_steps:
            if 'launch' in step.actions and 'browser' in step.raw_text.lower():
                websites = step.entities.get('websites', ['example.com'])
                urls = step.entities.get('urls', [f'https://{websites[0]}'])
                
                test_code_lines.append(
                    self.ui_templates.launch_browser_template(websites[0], urls[0])
                )
                test_code_lines.append(
                    self.ui_templates.visual_checkpoint_template(f"{websites[0].lower()}_homepage")
                )
            
            if 'click' in step.actions:
                sections = step.entities.get('sections', ['Home'])
                test_code_lines.append(
                    self.ui_templates.click_section_template(sections)
                )
            
            if 'extract' in step.actions:
                fields = step.entities.get('extract_fields', ['headline', 'link', 'date'])
                test_code_lines.append(
                    self.ui_templates.extract_carousel_data_template(fields)
                )
        
        return self.ui_templates.generate_ui_test_class(class_name, test_code_lines)
    
    def _generate_api_test(self, api_steps: List[TestStep], class_name: str) -> str:
        test_code_lines = []
        
        for step in api_steps:
            if 'send' in step.actions or 'post' in step.actions:
                api_urls = step.entities.get('api_urls', ['http://example.com/api'])
                fields = step.entities.get('extract_fields', ['headline', 'link'])
                
                test_code_lines.append(
                    self.api_templates.post_data_template(api_urls[0], fields)
                )
            
            if 'validate' in step.actions:
                api_urls = step.entities.get('api_urls', ['http://example.com/api'])
                test_code_lines.append(
                    self.api_templates.validate_data_template(api_urls[0])
                )
        
        return self.api_templates.generate_api_test_class(class_name, test_code_lines)
    
    def _generate_mobile_test(self, mobile_steps: List[TestStep], class_name: str) -> str:
        test_code_lines = []
        
        # Add mobile driver setup
        test_code_lines.append(self.mobile_templates.setup_mobile_driver_template())
        
        for step in mobile_steps:
            if 'extract' in step.actions:
                fields = step.entities.get('extract_fields', ['name', 'description', 'price'])
                test_code_lines.append(
                    self.mobile_templates.extract_product_data_template(fields)
                )
        
        # Add cleanup
        test_code_lines.append(self.mobile_templates.cleanup_mobile_template())
        
        return self.mobile_templates.generate_mobile_test_class(class_name, test_code_lines)
    
    def _generate_integration_test(self, all_steps: List[TestStep], class_name: str) -> str:
        template = '''"""
Auto-generated Integration Test Case
"""
import pytest
import requests
from HelperClasses.UI.Sample import Sample
from HelperClasses.API.ValidateAPI import ValidateAPI

@pytest.mark.usefixtures("init_driver")
class {class_name}:
    
    @pytest.mark.integration_test
    @pytest.mark.auto_generated
    def test_complete_testautothon_flow(self, extra, env, request, caseid):
        # Step 1: UI Data Extraction
        sample = Sample(self.driver, extra)
        ui_data = self._extract_ui_data(sample, env)
        
        # Step 2: API Interaction
        api_response = self._send_data_to_api(ui_data)
        
        # Step 3: Mobile Data Extraction
        mobile_data = self._extract_mobile_data()
        
        # Step 4: Final API Validation
        self._validate_all_data(api_response, mobile_data)
        
        print("TestAutothon automation flow completed successfully!")
    
    def _extract_ui_data(self, sample, env):
        return {{"headline": "Sample News", "link": "http://example.com", "team_name": "TestAutothon2824"}}
    
    def _send_data_to_api(self, data):
        return {{"item_id": "12345", "status": "success"}}
    
    def _extract_mobile_data(self):
        return {{"name": "Product", "price": "$100", "team_name": "TestAutothon2824"}}
    
    def _validate_all_data(self, api_response, mobile_data):
        assert api_response.get("status") == "success"
        assert mobile_data.get("team_name") == "TestAutothon2824"
'''
        return template.format(class_name=class_name)
    
    def save_generated_tests(self, generated_files: Dict[str, str]) -> List[str]:
        saved_files = []
        
        for filename, content in generated_files.items():
            filepath = os.path.join(self.output_dir, filename)
            with open(filepath, 'w', encoding='utf-8') as f:
                f.write(content)
            saved_files.append(filepath)
        
        return saved_files