"""Auto Test Generator CLI"""
import argparse
import os
import sys
from generators.test_generator import TestGenerator

def main():
    parser = argparse.ArgumentParser(description='Generate test scripts from TestAutothon problem statements')
    parser.add_argument('--problem-file', '-p', required=True, help='Path to problem statement text file')
    parser.add_argument('--test-name', '-n', default='AutoGenerated', help='Name for generated test classes')
    parser.add_argument('--output-dir', '-o', default='generated_tests', help='Output directory for generated tests')
    parser.add_argument('--preview', action='store_true', help='Preview generated code without saving')
    
    args = parser.parse_args()
    
    # Read problem statement
    try:
        with open(args.problem_file, 'r', encoding='utf-8') as f:
            problem_text = f.read()
    except FileNotFoundError:
        print(f"Error: Problem file '{args.problem_file}' not found")
        sys.exit(1)
    
    # Generate tests
    generator = TestGenerator(args.output_dir)
    generated_files = generator.generate_from_problem_statement(problem_text, args.test_name)
    
    if args.preview:
        print("=" * 80)
        print("GENERATED TEST CODE PREVIEW")
        print("=" * 80)
        
        for filename, content in generated_files.items():
            print(f"\n{'='*20} {filename} {'='*20}")
            print(content)
    else:
        saved_files = generator.save_generated_tests(generated_files)
        
        print(f"Generated {len(saved_files)} test files:")
        for filepath in saved_files:
            print(f"   {filepath}")
        
        print(f"\nTo run the generated tests:")
        print(f"   cd {args.output_dir}")
        print(f"   pytest -v")

if __name__ == "__main__":
    main()